app/base/urls.py
from django.urls import path
from app.base.views import \
    ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView

app_name = 'base'

urlpatterns = [
    path('nova', ProdutoCreateView.as_view(), name = 'nova'),
    path('editar/<pk>', ProdutoUpdateView.as_view(), name = 'editar'),
    path('exluir/<pk>', ProdutoDeleteView.as_view(), name = 'excluir'),
]

app/processamento/urls.py
from django.urls import path
from app.processamento.views import \
    RegraCreateView, RegraUpdateView, RegraDeleteView

app_name = 'processamento'

urlpatterns = [
    path('nova', RegraCreateView.as_view(), name = 'nova'),
    path('editar/<pk>', RegraUpdateView.as_view(), name = 'editar'),
    path('exluir/<pk>', RegraDeleteView.as_view(), name = 'excluir'),

]

desafio_sefaz/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from app.base.views import Home
from app.processamento.views import ClassificacaoViewSet

router = routers.DefaultRouter()
router.register(r'processamento', ClassificacaoViewSet )

urlpatterns = [
    path('', Home.as_view()),
    path('regra/', include('app.processamento.urls', namespace='processamento')),
    path('produto/', include('app.base.urls', namespace='base')),
    path('api/v1/', include(router.urls)),
    path('admin/', admin.site.urls),
]

app/base/models.py
from django.db import models

class Produto(models.Model):
    cor         = models.CharField('Cor', max_length=30)
    codigo_gtin = models.CharField('Codigo Gtin', max_length=20)
    tipo        = models.CharField('Tipo', max_length=50)
    processado  = models.BooleanField('Processado', default=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        return self.codigo_gtin

app/processamento/models.py
from django.db import models
from app.base.models import Produto


class Regra(models.Model):
    campo = models.CharField('Campo', max_length=50)
    valor = models.CharField('Valor', max_length=50)

    class Meta:
        verbose_name = 'Regra'
        verbose_name_plural = 'Regras'

    def __str__(self):
        return self.campo

class Classificacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    regra = models.ForeignKey(Regra, on_delete=models.CASCADE)
    resultado = models.BooleanField('Resultado', default=False)

    class Meta:
        verbose_name = 'Classificação'
        verbose_name_plural = 'Classificações'

    def __str__(self):
        return self.produto.codigo_gtin

app/base/forms.py
from django.forms import ModelForm
from app.base.models import Produto


class ProdutosCreationModelForm(ModelForm):
    class Meta:
        model = Produto
        fields = ['codigo_gtin','cor','tipo']

app/processamento/forms.py
from django.forms import ModelForm
from app.processamento.models import Regra

class RegrasCreationModelForm(ModelForm):

    class Meta:
        model = Regra
        fields = '__all__'

app/base/views.py
from django.views.generic import \
    TemplateView, CreateView, UpdateView, DeleteView
from app.base.forms import ProdutosCreationModelForm
from app.base.models import Produto
from app.processamento.motor_analise import set_classificacao


class Home(TemplateView):
    template_name = 'base/todos_produtos_classificados.html'


class ProdutoCreateView(CreateView):
    template_name = 'base/produtos_formulario.html'
    form_class = ProdutosCreationModelForm
    success_url = '/produto/nova'

    def form_valid(self, form):
        produto = form.save()
        set_classificacao(pk_produto=produto.pk)
        return super().form_valid(form)


class ProdutoUpdateView(UpdateView):
    model = Produto
    template_name = 'base/produtos_formulario.html'
    form_class = ProdutosCreationModelForm
    success_url = '/produto/nova'

class ProdutoDeleteView(DeleteView):
    model = Produto
    template_name = 'base/produtos_formulario.html'
    form_class = ProdutosCreationModelForm
    success_url = '/produto/nova'

app/processamento/views.py
from django.views.generic import CreateView, UpdateView, DeleteView
from rest_framework import viewsets
from app.processamento.forms import RegrasCreationModelForm
from app.processamento.models import Regra, Classificacao
from app.processamento.serializers import ClassificacaoSerializer


class RegraCreateView(CreateView):
    template_name = 'processamento/regras_formulario.html'
    form_class = RegrasCreationModelForm
    success_url = '/regra/nova'

class RegraUpdateView(UpdateView):
    model = Regra
    template_name = 'processamento/regras_formulario.html'
    form_class = RegrasCreationModelForm
    success_url = '/regra/nova'

class RegraDeleteView(DeleteView):
    model = Regra
    template_name = 'processamento/regras_formulario.html'
    form_class = RegrasCreationModelForm
    success_url = '/regra/nova'

class ClassificacaoViewSet(viewsets.ModelViewSet):
    queryset = Classificacao.objects.all()
    serializer_class = ClassificacaoSerializer

templates/base/produtos_formulario.html
{% extends 'estrutura.html' %}
{% load widget_tweaks %}
{% block content %}
   <div class="lead mb-3">Edição de Produtos</div>
	<div class="row">
		<div class="col-md-8 col-12">
			<table class="table table-hover">
			  <thead>
			    <tr>
			      <th scope="col">Codigo-Gtin</th>
			      <th scope="col">Cor</th>
				  <th scope="col">Tipo</th>
			      <th scope="col"></th>
				  <th scope="col"></th>
			    </tr>
			  </thead>
			  <tbody>
				  {% for produto in produtos %}
					 <tr>
					      <td>{{produto.codigo_gtin}}</td>
					      <td>{{produto.cor}}</td>
						  <td>{{produto.tipo}}</td>
					      <td><a href="{% url 'base:editar' produto.pk %}">Editar</a> </td>
					      <td><a href="{% url 'base:excluir' produto.pk %}">Excluir</a></td>
					 </tr>
				  {% endfor %}
			  </tbody>
			</table>
		</div>
		<div class="col-md-4 col-12">
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
				  <div class="form-group">
				    <label>{{ field.label }}</label>
				    {% render_field field class="form-control" %}
				  </div>
				{% endfor %}

				  <button type="submit" class="btn btn-primary">Enviar</button>
				  <a href="/" class="btn btn-secondary">Voltar</a>
			</form>
		</div>
	</div>
{% endblock %}

templates/base/todos_produtos_classificados.html
{% extends 'estrutura.html' %}
{% block content %}
<div class="lead mb-3">Classificação de Produtos</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Codigo-Gtin</th>
      <th scope="col">Cor</th>
      <th scope="col">Tipo</th>
	  <th scope="col">Processado</th>
	  <th scope="col">Classificação</th>
    </tr>
  </thead>
  <tbody>

	{% for p in processados %}
	    <tr>
	      <td>{{ p.produto.codigo_gtin }}</td>
	      <td>{{ p.produto.cor }}</td>
	      <td>{{ p.produto.tipo }}</td>
	      <td>{{ p.produto.processado|yesno:"Ok,Pendente" }}</td>
	      <td>Regra {{ p.regra.pk }}: {{ p.regra.campo|capfirst}} | {{ p.regra.valor  }}</td>
	      <td>Resultado: {{ p.resultado }}</td>
	    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/estrutura.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<title>Desafio Sefaz</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Desafio Sefaz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'processamento:nova' %}">Regras <span class="sr-only">(current)</span></a>
      </li>
	    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:nova' %}">Produtos <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Resultados
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="/api/v1/processamento">API consulta de classificação de produtos</a>
          <a class="dropdown-item" href="#"></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="container mt-5">
	{% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/processamento/regras_formulario.html
{% extends 'estrutura.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="lead mb-3">Edição de Regras</div>
	<div class="row">
		<div class="col-md-8 col-12">
			<table class="table table-hover">
			  <thead>
			    <tr>
			      <th scope="col">Campo</th>
			      <th scope="col">Valor</th>
				  <th scope="col"></th>
			      <th scope="col"></th>
			    </tr>
			  </thead>
			  <tbody>
				  {% for regra in regras %}
					 <tr>
					      <td>{{regra.campo}}</td>
					      <td>{{regra.valor}}</td>
					      <td><a href="{% url 'processamento:editar' regra.pk %}">Editar</a> </td>
					      <td><a href="{% url 'processamento:excluir' regra.pk %}">Excluir</a></td>
					 </tr>
				  {% endfor %}
			  </tbody>
			</table>
		</div>
		<div class="col-md-4 col-12">
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
				  <div class="form-group">
				    <label>{{ field.label }}</label>
				    {% render_field field class="form-control" %}
				  </div>
				{% endfor %}

				  <button type="submit" class="btn btn-primary">Enviar</button>
				  <a href="/" class="btn btn-secondary">Voltar</a>
			</form>
		</div>
	</div>
{% endblock %}